# Generated by Django 4.0.4 on 2022-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogs',
            field=models.ManyToManyField(null=True, to='forum.blog'),
        ),
    ]
