# Generated by Django 4.0.4 on 2022-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_blog_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogs',
            field=models.ManyToManyField(blank=True, to='forum.blog'),
        ),
    ]
